stages:
  - lint
  - test
  - build

lint:
  image: python:3.12-slim
  stage: lint
  script:
    - echo "Running lint stage"
    - pip install pylint
    - pylint main.py || true

test:
  image: python:3.12-slim
  stage: test
  script:
    - echo "Running test stage"
    - pip install pytest pytest-cov pytz sympy
    - pytest --cov=main --cov-report=xml --cov-fail-under=50
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - htmlcov/

build:
  image: python:3.12-slim
  stage: build
  script:
    - echo "Running build stage"
    - pip install -r requirements.txt

  only:
    - main
